### ISSUE TITLE
Deadlock happens after scaling SpMSpV to 8 HBM channels

### ISSUE THREAD

**Issue by Huyuwei** [cornell-zhang/GraphLily#2]
After fusing the three interfaces of one matrix partition (`partptr`, `indptr`, `packets`) into a single interface (commit: 1409b0d4085d37d975e2a64ebb1afbdbadaeb682), we are now able to scale SpMSpV to up to 32 channels.

Deadlock happens when I benchmark an 8-channel SpMSpV. On `uniform_10K_10`, it passed the first iteration and ran into deadlock after several iterations; on `ogbl_ppa_576K_42M`, it ran into deadlock at the first iteration. With hardware emulation, there is no deadlock. I tried increasing the FIFO depth, but deadlock still happens.

@yxd97 Please take a look at this issue later when you have time. It might be related to the shuffler. Also check the data loader and stream merger.

**Comment by yxd97** [comment]
Could you try to build and run the design with the shuffle unit removed? I will take a look at the codes later.
Also the "iteration" refers to the loop in the kernel, or your running the kernel several times non-stop?

**Comment by Huyuwei** [comment]
Removing the shuffler doesn't solve the issue. I am going to check the data loader and stream merger.

**Comment by Huyuwei** [comment]
close the issue since we are going to open-source the repo
